language: ruby
rvm:
- 2.3.0
cache: bundler
sudo: false
before_install:
- gem update --system
- gem --version
before_script:
- psql -c 'create database myfamilyweb_test;' -U postgres
- cp config/database.travis.yml config/database.yml
script:
- export TRAVIS=true
- export RACK_ENV=test
- rubocop .
- bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake factory_girl:lint
- bundle exec rake
addons:
  postgresql: "9.4"
