default: &default
  adapter: postgresql
  database: myfamilyweb_development
  username: development
  password: development
  host: 127.0.0.1

development:
  <<: *default

test: &test
  <<: *default
  database: myfamilyweb_test
  username: test
  password: test

cucumber:
  <<: *test