#!/usr/bin/env ruby

vendored_cucumber_bin = Dir[
  "#{File.dirname(__FILE__)}/../vendor/{gems,plugins}/cucumber*/bin/cucumber"]
cucumber_bin = vendored_cucumber_bin.first
if cucumber_bin
  load File.expand_path(cucumber_bin)
else
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'cucumber'
  load Cucumber::BINARY
end
